# fly.toml app configuration file generated for foundry-staging-nats-cluster on 2023-05-13T12:17:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foundry-staging-nats-cluster"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 9222
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 2000
    soft_limit = 1750
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source="foundry_staging_nats_cluster_data"
  destination="/data"
